version: '3.1'
services:
  app:
    container_name: appdockercont
    image: appdockerimag
    build: ./
    ports:
      - "3000:3000"
    depends_on:
      - postgresql
  postgresql:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=123456789Oury
      - POSTGRES_USER=postgres
      - POSTGRES_DB=demotodock
    ports:
      - "5432:5432"
