version: '3'
services:
  catalogapp:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - h2db
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:dbAPI
  h2db:
    image: oscarfonts/h2
    ports:
      - "1521:1521"

